# Generated by Django 4.2.17 on 2024-12-16 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('face_encoding', models.BinaryField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user_data',
            },
        ),
    ]
